title: clgzyh Blog
description: clgzyh Blog

url: https://clgzyh.github.io

# 分页配置
paginate: 10
paginate_path: "/page:num/"
permalink: /:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]


navigation:
 - title: 主页
   url: /
 - title: 文章
   url: /articles/
 - title: 速查手册
   url: /cheatsheets/
 - title: 分类
   url: /categories/
 - title: 关于
   url: /about/
 - title: 捐赠
   url: /donate/

social:
   github: clgzyh


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      cheatsheet: false    # 新增：是否为速查手册

host: 0.0.0.0