title: clgzyh Blog
description: clgzyh Blog

url: https://clgzyh.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
 - title: 主页
   url: /index.html
 - title: 文章
   url: /articles
 - title: 速查手册
   url: /cheatsheets
 - title: 分类
   url: /categories
 - title: 关于
   url: /about
 - title: 捐赠
   url: /donate

social:
   github: clgzyh
   # linkedin: in/yanan-zhao-7691317b?trk=hp-identity-photo
   # facebook: profile.php?id=100014334455077
   # email: arthurchiao@hotmail.com

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      comments: false

# google_analytics: "G-5SFP2TKSL7"

# development configurations
host: 0.0.0.0